---
- name: Ensure docker.io is installed and up-to-date
  hosts: all
  become: yes
  tasks:

    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Install or update docker.io to the latest version
      apt:
        name: docker.io
        state: latest

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes